---
- name: Bootstrap Nodes
  hosts: all
  gather_facts: no
  tasks:
    - name: Install Python
      raw: apt-get -y -qq install python3

    - name: Download Docker installation script
      get_url:
        url: https://get.docker.com
        dest: /home/ubuntu/get_docker.sh
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Run Script
      command: /home/ubuntu/get_docker.sh

- name: Init Swarm Manager
  hosts: manager
  gather_facts: no
  tasks:
    - name: Copy cluster config over to master
      copy:
        src: resources/docker-compose.yml
        dest: /home/ubuntu/docker-compose.yml
        owner: ubuntu
        group: ubuntu

    - name: Init Swarm
      command: docker swarm init

    - name: Get worker token
      command: docker swarm join-token worker -q
      register: worker_token

- name: Connect workers to swarm
  hosts: workers
  gather_facts: no
  vars:
    token: "{{ hostvars[groups['manager'][0]]['worker_token']['stdout'] }}"
    master: "{{ hostvars[groups['manager'][0]]['inventory_hostname'] }}"
  tasks:
    - name: Join swarm cluster as a worker
      command: docker swarm join --token {{ token }} {{ master }}:2377
      register: worker

- name: Deploy Flink Cluster
  hosts: manager
  gather_facts: no
  vars:
    num_taskmanagers: "{{ lookup('env', 'TF_VAR_cluster_size') | int - 1 }}"
  tasks:
    - name: Deploy Docker Stack
      command: docker stack deploy -c docker-compose.yml flink

    - name: Deploy desired number of taskmanagers
      command: docker service scale flink_taskmanager={{ num_taskmanagers }}
...