---
- name: Install Java on benchstand
  hosts: bench
  become: true
  gather_facts: false
  tasks:
    - name: Install Java 8
      apt:
        name: openjdk-8-jre
        update_cache: true
        install_recommends: false

- name: Install Docker
  hosts: manager:workers
  gather_facts: false
  tasks:
    - name: Download Docker installation script
      get_url:
        url: https://get.docker.com
        dest: ~/get_docker.sh
        mode: '0755'

    - name: Run script
      command: ~/get_docker.sh

- name: Initialize swarm manager
  hosts: manager
  become: true
  gather_facts: false
  tasks:
    - name: Init swarm
      command: docker swarm init

    - name: Get worker token
      command: docker swarm join-token worker -q
      register: worker_token

- name: Connect workers to swarm
  hosts: workers
  become: true
  gather_facts: false
  vars:
    token: "{{ hostvars[groups['manager'][0]]['worker_token']['stdout'] }}"
    manager: "{{ hostvars[groups['manager'][0]]['inventory_hostname'] }}"
  tasks:
    - name: Join swarm as a worker
      command: docker swarm join --token {{ token }} {{ manager }}:2377

- name: Deploy Flink cluster
  hosts: manager
  gather_facts: false
  vars:
    num_taskmanagers: "{{ lookup('env', 'TF_VAR_cluster_size') | int - 2 }}"
  tasks:
    - name: Copy cluster config to the manager
      template:
        src: resources/docker-compose.yml.j2
        dest: ~/docker-compose.yml

    - name: Deploy Docker Stack
      become: true
      command: docker stack deploy -c docker-compose.yml flink

- name: Run benchmark
  hosts: bench
  gather_facts: false
  tasks:
    - name: Copy test data to bench
      copy:
        src: ../../TestData/comsn10.txt
        dest: ~/comsn10.txt

    - name: Assemble benchmark config
      template:
        src: resources/bench.conf.j2
        dest: ~/bench.conf

    - name: Copy benchmark jar to the benchstand
      copy:
        src: resources/BenchStand.jar
        dest: ~/BenchStand.jar

#    - name: Run benchmark
#      command: java -jar BenchStand.jar bench.conf
...
